//// <auto-generated />
//using System;
//using Category_Master.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace Category_Master.Migrations
//{
//    [DbContext(typeof(AppDbContext))]
//    [Migration("20250124114844_AddImageMstTbl")]
//    partial class AddImageMstTbl
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.1")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Category_Master.Models.CategoryMst", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("CategoryName")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.HasKey("Id");

//                    b.ToTable("Categories");
//                });

//            modelBuilder.Entity("Category_Master.Models.ImageMst", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CategoriesId")
//                        .HasColumnType("int");

//                    b.Property<int>("CategoryId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("CreatedDate")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("GETDATE()");

//                    b.Property<string>("ImageMIMEType")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("ImageName")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .HasColumnType("nvarchar(255)");

//                    b.Property<long>("ImageSize")
//                        .HasColumnType("bigint");

//                    b.Property<string>("ImageType")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("ImageURL")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .HasColumnType("nvarchar(255)");

//                    b.Property<int>("SubCategoriesId")
//                        .HasColumnType("int");

//                    b.Property<int>("SubCategoryId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("UpdatedDate")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("CategoriesId");

//                    b.HasIndex("CategoryId");

//                    b.HasIndex("SubCategoriesId");

//                    b.HasIndex("SubCategoryId");

//                    b.ToTable("ImageMsts");
//                });

//            modelBuilder.Entity("Category_Master.Models.SubCategoryMst", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CategoryId")
//                        .HasColumnType("int");

//                    b.Property<string>("SubCategoryName")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.HasKey("Id");

//                    b.HasIndex("CategoryId");

//                    b.ToTable("SubCategories");
//                });

//            modelBuilder.Entity("Category_Master.Models.ImageMst", b =>
//                {
//                    b.HasOne("Category_Master.Models.CategoryMst", "Categories")
//                        .WithMany()
//                        .HasForeignKey("CategoriesId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Category_Master.Models.CategoryMst", null)
//                        .WithMany()
//                        .HasForeignKey("CategoryId")
//                        .OnDelete(DeleteBehavior.NoAction)
//                        .IsRequired();

//                    b.HasOne("Category_Master.Models.SubCategoryMst", "SubCategories")
//                        .WithMany()
//                        .HasForeignKey("SubCategoriesId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Category_Master.Models.SubCategoryMst", null)
//                        .WithMany()
//                        .HasForeignKey("SubCategoryId")
//                        .OnDelete(DeleteBehavior.NoAction)
//                        .IsRequired();

//                    b.Navigation("Categories");

//                    b.Navigation("SubCategories");
//                });

//            modelBuilder.Entity("Category_Master.Models.SubCategoryMst", b =>
//                {
//                    b.HasOne("Category_Master.Models.CategoryMst", null)
//                        .WithMany()
//                        .HasForeignKey("CategoryId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
